<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Treatments;
use App\Models\Client;
use App\Models\User;
use App\Models\TreatmentType;

class TreatmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = Client::all();
        $users = User::all();
        $treatmentTypes = TreatmentType::all();

        $treatments = [
            [
                'client_id' => $clients[0]->id,
                'user_id' => $users[1]->id,
                'treatment_type_id' => $treatmentTypes[0]->id,
                'treatment_date' => '2025-12-01',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'Facial Treatment',
                'treatment_reason' => 'Deep cleansing and hydration for dry skin',
                'notes' => 'Client responded well, follow-up in 4 weeks',
                'status' => 'completed',
                'treatment_amount' => 150.00,
                'vat_amount' => 7.50,
                'discount' => 0,
                'total_amount_received' => 157.50,
                'payment_type' => 'card',
            ],
            [
                'client_id' => $clients[1]->id,
                'user_id' => $users[2]->id,
                'treatment_type_id' => $treatmentTypes[1]->id,
                'treatment_date' => '2025-12-03',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'Chemical Peel',
                'treatment_reason' => 'Acne scarring treatment',
                'notes' => 'Light peel applied, mild redness expected for 2 days',
                'status' => 'completed',
                'treatment_amount' => 200.00,
                'vat_amount' => 10.00,
                'discount' => 0,
                'total_amount_received' => 210.00,
                'payment_type' => 'cash',
            ],
            [
                'client_id' => $clients[2]->id,
                'user_id' => $users[1]->id,
                'treatment_type_id' => $treatmentTypes[3]->id,
                'treatment_date' => '2025-12-05',
                'therapist_name' => 'Staff Member',
                'treatment_name' => 'Botox Injection',
                'treatment_reason' => 'Forehead and crow\'s feet wrinkle reduction',
                'notes' => 'First time client, 20 units used',
                'status' => 'completed',
                'treatment_amount' => 350.00,
                'vat_amount' => 17.50,
                'discount' => 0,
                'total_amount_received' => 367.50,
                'payment_type' => 'card',
            ],
            [
                'client_id' => $clients[3]->id,
                'user_id' => $users[2]->id,
                'treatment_type_id' => $treatmentTypes[5]->id,
                'treatment_date' => '2025-12-07',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'Laser Hair Removal',
                'treatment_reason' => 'Full legs hair removal - session 3 of 6',
                'notes' => 'Good progress, next session in 6 weeks',
                'status' => 'completed',
                'treatment_amount' => 250.00,
                'vat_amount' => 12.50,
                'discount' => 25.00,
                'total_amount_received' => 237.50,
                'payment_type' => 'tabby',
            ],
            [
                'client_id' => $clients[4]->id,
                'user_id' => $users[1]->id,
                'treatment_type_id' => $treatmentTypes[6]->id,
                'treatment_date' => '2025-12-10',
                'therapist_name' => 'Staff Member',
                'treatment_name' => 'HydraFacial',
                'treatment_reason' => 'Monthly skin maintenance',
                'notes' => 'Used fragrance-free products per client preference',
                'status' => 'completed',
                'treatment_amount' => 220.00,
                'vat_amount' => 11.00,
                'discount' => 0,
                'total_amount_received' => 231.00,
                'payment_type' => 'cash',
            ],
            [
                'client_id' => $clients[5]->id,
                'user_id' => $users[2]->id,
                'treatment_type_id' => $treatmentTypes[4]->id,
                'treatment_date' => '2025-12-12',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'Dermal Filler',
                'treatment_reason' => 'Cheek volume restoration',
                'notes' => '1ml per side, very natural result',
                'status' => 'completed',
                'treatment_amount' => 400.00,
                'vat_amount' => 20.00,
                'discount' => 0,
                'total_amount_received' => 420.00,
                'payment_type' => 'bank_transfer',
            ],
            [
                'client_id' => $clients[6]->id,
                'user_id' => $users[1]->id,
                'treatment_type_id' => $treatmentTypes[8]->id,
                'treatment_date' => '2025-12-15',
                'therapist_name' => 'Staff Member',
                'treatment_name' => 'Lip Enhancement',
                'treatment_reason' => 'Lip volume and shape improvement',
                'notes' => 'VIP client - 10% discount applied',
                'status' => 'completed',
                'treatment_amount' => 300.00,
                'vat_amount' => 15.00,
                'discount' => 30.00,
                'total_amount_received' => 285.00,
                'payment_type' => 'card',
            ],
            [
                'client_id' => $clients[0]->id,
                'user_id' => $users[2]->id,
                'treatment_type_id' => $treatmentTypes[7]->id,
                'treatment_date' => '2025-12-18',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'PRP Therapy',
                'treatment_reason' => 'Hair restoration treatment - session 1',
                'notes' => 'Blood drawn and processed, PRP injected into scalp',
                'status' => 'completed',
                'treatment_amount' => 500.00,
                'vat_amount' => 25.00,
                'discount' => 0,
                'total_amount_received' => 525.00,
                'payment_type' => 'tamara',
            ],
            [
                'client_id' => $clients[1]->id,
                'user_id' => $users[1]->id,
                'treatment_type_id' => $treatmentTypes[2]->id,
                'treatment_date' => '2025-12-20',
                'therapist_name' => 'Staff Member',
                'treatment_name' => 'Microdermabrasion',
                'treatment_reason' => 'Skin texture improvement',
                'notes' => null,
                'status' => 'completed',
                'treatment_amount' => 180.00,
                'vat_amount' => 9.00,
                'discount' => 0,
                'total_amount_received' => 189.00,
                'payment_type' => 'cash',
            ],
            [
                'client_id' => $clients[2]->id,
                'user_id' => $users[2]->id,
                'treatment_type_id' => $treatmentTypes[9]->id,
                'treatment_date' => '2025-12-22',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'Skin Tightening',
                'treatment_reason' => 'Jawline and neck tightening',
                'notes' => 'Recommended 3 more sessions for optimal results',
                'status' => 'completed',
                'treatment_amount' => 280.00,
                'vat_amount' => 14.00,
                'discount' => 0,
                'total_amount_received' => 294.00,
                'payment_type' => 'card',
            ],
            [
                'client_id' => $clients[4]->id,
                'user_id' => $users[1]->id,
                'treatment_type_id' => $treatmentTypes[0]->id,
                'treatment_date' => '2026-01-05',
                'therapist_name' => 'Staff Member',
                'treatment_name' => 'Facial Treatment',
                'treatment_reason' => 'Post-holiday skin refresh',
                'notes' => null,
                'status' => 'pending',
                'treatment_amount' => 150.00,
                'vat_amount' => 7.50,
                'discount' => 0,
                'total_amount_received' => 0,
                'payment_type' => null,
            ],
            [
                'client_id' => $clients[5]->id,
                'user_id' => $users[2]->id,
                'treatment_type_id' => $treatmentTypes[3]->id,
                'treatment_date' => '2026-01-08',
                'therapist_name' => 'Sarah Johnson',
                'treatment_name' => 'Botox Injection',
                'treatment_reason' => 'Follow-up treatment',
                'notes' => null,
                'status' => 'pending',
                'treatment_amount' => 350.00,
                'vat_amount' => 17.50,
                'discount' => 0,
                'total_amount_received' => 0,
                'payment_type' => null,
            ],
        ];

        foreach ($treatments as $treatment) {
            Treatments::create($treatment);
        }
    }
}
